//! Mobile confirmations: the approvals the Steam Mobile app shows for trade
//! offers and market listings, and that gate them from completing until
//! approved.
//!
//! Steam signs every confirmation request with the Steam Desktop
//! Authenticator (SDA) scheme, the same one third-party tools like SDA
//! itself and ASF use:
//!
//! ```text
//! key = base64(HMAC_SHA1(identity_secret, big_endian_u64(unix_time) ‖ tag))
//! ```
//!
//! `tag` is ASCII, truncated to 32 bytes before hashing. Different operations
//! use different tags: `"list"` to fetch the pending set ([`list`]), `"accept"`
//! to approve one ([`accept`]). The two request URLs also both carry `m=react`,
//! which identifies the modern ("react") confirmation UI Steam serves this
//! request to; older `m=android2`/`m=ios` responses are not handled here.
//!
//! ## Where `identity_secret` and `device_id` come from
//!
//! Both are **imported from a Steam Desktop Authenticator maFile**, not
//! derived or generated by this crate. `identity_secret` is the maFile's
//! `identity_secret` field, base64-decoded to raw bytes before it reaches
//! this module (functions here take `&[u8]`, not the base64 string).
//! `device_id` is the maFile's `device_id` field, generally of the form
//! `android:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.
//!
//! This crate implements no authenticator-enrolment flow
//! (`AddAuthenticator` / `FinalizeAddAuthenticator`): there is no way to
//! obtain either value from `steamroids` alone. A caller needs an existing
//! maFile, from the Steam Desktop Authenticator app or an equivalent
//! enrolment done elsewhere, before calling into this module.

use std::time::{SystemTime, UNIX_EPOCH};

use base64::Engine;
use hmac::{Hmac, Mac};
use serde::Deserialize;

use crate::error::Error;
use crate::web::WebSession;
use crate::Result;

type HmacSha1 = Hmac<sha1::Sha1>;

const GETLIST_URL: &str = "https://steamcommunity.com/mobileconf/getlist";
const AJAXOP_URL: &str = "https://steamcommunity.com/mobileconf/ajaxop";

/// SDA truncates the tag to this many bytes before hashing.
const TAG_MAX_LEN: usize = 32;

/// One pending mobile confirmation.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct Confirmation {
    /// Confirmation id (`cid` on the wire). Needed, together with
    /// [`Self::nonce`], to [`accept`] this confirmation.
    pub id: String,
    /// Confirmation nonce (`ck` on the wire). Steam pairs a fresh nonce with
    /// every confirmation id; the two must be sent together and neither is
    /// valid alone.
    pub nonce: String,
    /// Steam's confirmation type code, from the response's `type` field
    /// (renamed here because `type` is a Rust keyword). Kept as the raw code
    /// rather than an enum: third-party Steam confirmation tools document a
    /// handful of values (trade offer, market listing, phone number change,
    /// account recovery, ...), but this crate has not independently
    /// confirmed the full set against a live response, so no claim is made
    /// about which numbers mean what.
    pub kind: i32,
    /// Id of whatever this confirmation is *for*: a trade offer id or a
    /// market listing id, depending on `kind`. Sent by Steam as a JSON
    /// string (large ids do not round-trip cleanly as JSON numbers, the
    /// same reason `QueryTime`'s `server_time` is a string; see
    /// [`crate::auth::totp`]), so kept as `String` rather than parsed to an
    /// integer.
    pub creator_id: String,
}

/// Fetch the account's pending mobile confirmations.
///
/// `identity_secret` and `device_id` come from a Steam Desktop Authenticator
/// maFile; see the [module docs](self) for where to get them. The request
/// goes out over `web`, so it carries `web`'s session cookie and leaves
/// through `web`'s proxy, same as every other [`WebSession::get`] call.
///
/// An empty result means no confirmations are pending; it is not
/// distinguished from a transient blip (check again shortly) in any way,
/// since Steam's response gives no such signal.
///
/// # Errors
///
/// [`Error::HmacKey`] if `identity_secret` cannot key an HMAC-SHA1 (in
/// practice this never happens: HMAC accepts any key length). Any transport
/// error from [`WebSession::get`]. [`Error::Network`] if the response body
/// is not the expected JSON shape. [`Error::Remote`] if Steam's response
/// parses but reports `"success": false`.
pub async fn list(
    web: &WebSession,
    identity_secret: &[u8],
    device_id: &str,
) -> Result<Vec<Confirmation>> {
    let time = now_unix()?;
    let key = confirmation_key(identity_secret, time, "list")?;
    let url = getlist_url(device_id, web.steam_id(), &key, time);
    let body = web.get(&url).await?;
    parse_getlist_response(&body)
}

/// Approve a pending confirmation.
///
/// **This mutates account state.** Calling this approves the underlying
/// trade offer or market listing exactly as tapping "Confirm" in the Steam
/// Mobile app would: a trade offer executes (items change hands), a market
/// listing goes live for sale. There is no dry-run mode and no undo through
/// this API once Steam accepts the request. Callers must be certain
/// `conf` is the confirmation they mean to approve: fetch it fresh from
/// [`list`] and inspect [`Confirmation::kind`] / [`Confirmation::creator_id`]
/// before calling this, rather than replaying a stale or guessed id/nonce
/// pair.
///
/// `identity_secret` and `device_id` come from a Steam Desktop Authenticator
/// maFile; see the [module docs](self) for where to get them.
///
/// # Errors
///
/// [`Error::HmacKey`] if `identity_secret` cannot key an HMAC-SHA1 (in
/// practice this never happens). Any transport error from
/// [`WebSession::get`]. [`Error::Network`] if the response body is not the
/// expected JSON shape. [`Error::Remote`] if Steam's response parses but
/// reports `"success": false`; this includes the confirmation having
/// already been actioned, expired, or the id/nonce pair being wrong.
pub async fn accept(
    web: &WebSession,
    identity_secret: &[u8],
    device_id: &str,
    conf: &Confirmation,
) -> Result<()> {
    let time = now_unix()?;
    let key = confirmation_key(identity_secret, time, "accept")?;
    let url = ajaxop_url(device_id, web.steam_id(), &key, time, conf);
    let body = web.get(&url).await?;
    parse_ajaxop_response(&body)
}

/// The SDA signing key: `base64(HMAC_SHA1(identity_secret, be_u64(time) ‖ tag[..32]))`.
fn confirmation_key(identity_secret: &[u8], time: u64, tag: &str) -> Result<String> {
    let mut mac = HmacSha1::new_from_slice(identity_secret).map_err(|_| Error::HmacKey)?;
    mac.update(&time.to_be_bytes());
    let tag_bytes = tag.as_bytes();
    mac.update(&tag_bytes[..tag_bytes.len().min(TAG_MAX_LEN)]);
    let sig = mac.finalize().into_bytes();
    Ok(base64::engine::general_purpose::STANDARD.encode(sig))
}

fn now_unix() -> Result<u64> {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .map_err(|_| Error::InvalidConfig("system clock before epoch".into()))
}

fn getlist_url(device_id: &str, steam_id: u64, key: &str, time: u64) -> String {
    // static base always parses
    let mut url = url::Url::parse(GETLIST_URL).expect("static url parses");
    url.query_pairs_mut()
        .append_pair("p", device_id)
        .append_pair("a", &steam_id.to_string())
        .append_pair("k", key)
        .append_pair("t", &time.to_string())
        .append_pair("m", "react")
        .append_pair("tag", "list");
    url.to_string()
}

fn ajaxop_url(device_id: &str, steam_id: u64, key: &str, time: u64, conf: &Confirmation) -> String {
    // static base always parses
    let mut url = url::Url::parse(AJAXOP_URL).expect("static url parses");
    url.query_pairs_mut()
        .append_pair("op", "allow")
        .append_pair("p", device_id)
        .append_pair("a", &steam_id.to_string())
        .append_pair("k", key)
        .append_pair("t", &time.to_string())
        .append_pair("m", "react")
        .append_pair("tag", "accept")
        .append_pair("cid", &conf.id)
        .append_pair("ck", &conf.nonce);
    url.to_string()
}

/// JSON shape of `mobileconf/getlist`'s response, as documented by
/// third-party Steam confirmation implementations (SDA, ASF,
/// `node-steamcommunity`'s confirmation helper). **Not independently
/// verified against a live Steam response**: no test account with a
/// pending confirmation was available while writing this. Kept
/// deliberately narrow: only the fields [`Confirmation`] actually needs are
/// decoded, and unrecognised extra fields are ignored rather than rejected.
#[derive(Deserialize)]
struct GetListResponse {
    success: bool,
    #[serde(default)]
    conf: Vec<RawConfirmation>,
}

#[derive(Deserialize)]
struct RawConfirmation {
    id: String,
    nonce: String,
    #[serde(rename = "type")]
    kind: i32,
    creator_id: String,
}

fn parse_getlist_response(body: &str) -> Result<Vec<Confirmation>> {
    let parsed: GetListResponse = serde_json::from_str(body)
        .map_err(|e| Error::Network(format!("mobileconf getlist: unparseable response: {e}")))?;
    if !parsed.success {
        return Err(Error::Remote(format!(
            "mobileconf getlist: success=false: {body}"
        )));
    }
    Ok(parsed
        .conf
        .into_iter()
        .map(|c| Confirmation {
            id: c.id,
            nonce: c.nonce,
            kind: c.kind,
            creator_id: c.creator_id,
        })
        .collect())
}

/// JSON shape of `mobileconf/ajaxop`'s response. Same caveat as
/// [`GetListResponse`]: modelled off third-party implementations, not
/// independently observed live.
#[derive(Deserialize)]
struct AjaxOpResponse {
    success: bool,
}

fn parse_ajaxop_response(body: &str) -> Result<()> {
    let parsed: AjaxOpResponse = serde_json::from_str(body)
        .map_err(|e| Error::Network(format!("mobileconf ajaxop: unparseable response: {e}")))?;
    if !parsed.success {
        return Err(Error::Remote(format!(
            "mobileconf ajaxop: success=false: {body}"
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 20 zero bytes, same convention as `totp.rs`'s `ZERO_SECRET_B64`.
    const ZERO_SECRET: [u8; 20] = [0u8; 20];
    const FIXED_TIME: u64 = 1_700_000_000;

    /// Known-answer vectors independently computed with a throwaway Python
    /// script (`hmac`/`hashlib`/`base64`, big-endian `time.to_bytes(8,
    /// "big")`), not derived from this file. Any change here means the
    /// derivation drifted: byte order, tag truncation, or the base64
    /// alphabet.
    #[test]
    fn confirmation_key_matches_known_answer_vectors() {
        assert_eq!(
            confirmation_key(&ZERO_SECRET, FIXED_TIME, "list").unwrap(),
            "V2bjan+zs4lEg2KYiY/UAq+YHg0="
        );
        assert_eq!(
            confirmation_key(&ZERO_SECRET, FIXED_TIME, "accept").unwrap(),
            "xcRxWoWj1bB8hlE5A64X45bGDDk="
        );
    }

    #[test]
    fn confirmation_key_different_tags_produce_different_keys() {
        let list_key = confirmation_key(&ZERO_SECRET, FIXED_TIME, "list").unwrap();
        let accept_key = confirmation_key(&ZERO_SECRET, FIXED_TIME, "accept").unwrap();
        assert_ne!(list_key, accept_key);
    }

    #[test]
    fn confirmation_key_different_times_produce_different_keys() {
        let t1 = confirmation_key(&ZERO_SECRET, FIXED_TIME, "list").unwrap();
        let t2 = confirmation_key(&ZERO_SECRET, FIXED_TIME + 1, "list").unwrap();
        assert_ne!(t1, t2);
    }

    /// Pins truncation at exactly 32 bytes, not some other length: a 40-byte
    /// tag of 40 *distinct* characters must hash identically to its first 32
    /// bytes, and differently from its first 16 (a uniform-byte tag like
    /// "aaaa..." would not catch a wrong truncation length, since any
    /// prefix of it looks the same -- these 40 chars are all different).
    /// Expected values independently computed the same way as the vectors
    /// above.
    #[test]
    fn confirmation_key_truncates_tag_to_32_bytes() {
        let long_tag = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN";
        assert_eq!(long_tag.len(), 40);
        let truncated_tag = &long_tag[..32];

        let long_key = confirmation_key(&ZERO_SECRET, FIXED_TIME, long_tag).unwrap();
        let truncated_key = confirmation_key(&ZERO_SECRET, FIXED_TIME, truncated_tag).unwrap();
        assert_eq!(long_key, truncated_key);
        assert_eq!(long_key, "Bno+GezLuABhKZaEpHpMKW6wMYo=");

        // a wrong truncation length must not coincidentally match
        let short_key = confirmation_key(&ZERO_SECRET, FIXED_TIME, &long_tag[..16]).unwrap();
        assert_ne!(long_key, short_key);
    }

    #[test]
    fn getlist_url_carries_the_react_ui_marker_and_list_tag() {
        let url = getlist_url("android:device-id", 76_561_198_000_000_001, "abc+/=key", 42);
        assert!(url.starts_with("https://steamcommunity.com/mobileconf/getlist?"));
        assert!(url.contains("m=react"));
        assert!(url.contains("tag=list"));
        assert!(url.contains("a=76561198000000001"));
        assert!(url.contains("t=42"));
        // base64 special chars must be percent-encoded, not sent raw
        assert!(!url.contains('+'));
        assert!(url.contains("%2B") || url.contains("%3D"));
    }

    #[test]
    fn ajaxop_url_carries_allow_op_and_the_confirmation_pair() {
        let conf = Confirmation {
            id: "123".to_string(),
            nonce: "nonce-value".to_string(),
            kind: 2,
            creator_id: "999".to_string(),
        };
        let url = ajaxop_url("android:device-id", 1, "key", 42, &conf);
        assert!(url.starts_with("https://steamcommunity.com/mobileconf/ajaxop?"));
        assert!(url.contains("op=allow"));
        assert!(url.contains("m=react"));
        assert!(url.contains("tag=accept"));
        assert!(url.contains("cid=123"));
        assert!(url.contains("ck=nonce-value"));
    }

    #[test]
    fn parses_a_getlist_response_with_one_confirmation() {
        let body = r#"{"success":true,"conf":[{"id":"6516960720","type":2,"creator_id":"3242527830385650860","nonce":"AbCdEf123"}]}"#;
        let confs = parse_getlist_response(body).unwrap();
        assert_eq!(confs.len(), 1);
        assert_eq!(confs[0].id, "6516960720");
        assert_eq!(confs[0].kind, 2);
        assert_eq!(confs[0].creator_id, "3242527830385650860");
        assert_eq!(confs[0].nonce, "AbCdEf123");
    }

    #[test]
    fn parses_a_getlist_response_with_no_confirmations() {
        let body = r#"{"success":true,"conf":[]}"#;
        assert!(parse_getlist_response(body).unwrap().is_empty());
    }

    #[test]
    fn getlist_response_missing_conf_key_reads_as_empty() {
        // permissive: absence of "conf" alongside success:true is treated as
        // "nothing pending", not a hard failure.
        let body = r#"{"success":true}"#;
        assert!(parse_getlist_response(body).unwrap().is_empty());
    }

    #[test]
    fn getlist_response_success_false_is_a_remote_error() {
        let body = r#"{"success":false}"#;
        let err = parse_getlist_response(body).unwrap_err();
        assert!(matches!(err, Error::Remote(_)), "{err:?}");
    }

    #[test]
    fn getlist_response_garbage_is_a_network_error() {
        let err = parse_getlist_response("not json").unwrap_err();
        assert!(matches!(err, Error::Network(_)), "{err:?}");
    }

    #[test]
    fn parses_an_ajaxop_success_response() {
        assert!(parse_ajaxop_response(r#"{"success":true}"#).is_ok());
    }

    #[test]
    fn ajaxop_response_success_false_is_a_remote_error() {
        let err = parse_ajaxop_response(r#"{"success":false}"#).unwrap_err();
        assert!(matches!(err, Error::Remote(_)), "{err:?}");
    }

    #[test]
    fn ajaxop_response_garbage_is_a_network_error() {
        let err = parse_ajaxop_response("not json").unwrap_err();
        assert!(matches!(err, Error::Network(_)), "{err:?}");
    }
}
